
 name: HTMl WorkFLow

 on: [push]

 jobs:
   run-shell-commands:
     runs-on: ubuntu-latest
     steps:
       - name: echo a string
         run: "hello world"
         -name: Multiline command
         run: |
           node -v
           npm -v

      
  